//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginServiceClient.ServiceReferenceLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLogin.IloginService")]
    public interface IloginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginService/ValidateLogin", ReplyAction="http://tempuri.org/IloginService/ValidateLoginResponse")]
        bool ValidateLogin(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginService/ValidateLogin", ReplyAction="http://tempuri.org/IloginService/ValidateLoginResponse")]
        System.Threading.Tasks.Task<bool> ValidateLoginAsync(string user, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IloginServiceChannel : loginServiceClient.ServiceReferenceLogin.IloginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IloginServiceClient : System.ServiceModel.ClientBase<loginServiceClient.ServiceReferenceLogin.IloginService>, loginServiceClient.ServiceReferenceLogin.IloginService {
        
        public IloginServiceClient() {
        }
        
        public IloginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IloginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateLogin(string user, string pass) {
            return base.Channel.ValidateLogin(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateLoginAsync(string user, string pass) {
            return base.Channel.ValidateLoginAsync(user, pass);
        }
    }
}
